#!/bin/bash
set -eu

rm docs/js/*

node_modules/.bin/elm make src/Tutorial_04_VanillaElm.elm         --output=docs/js/tutorial-04-vanilla-elm.js           --debug
node_modules/.bin/elm make src/Tutorial_05_ElmAnimatorInline1.elm --output=docs/js/tutorial-05-elm-animator-inline-1.js --debug

node_modules/.bin/terser docs/js/tutorial-04-vanilla-elm.js           --no-rename --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters=true,keep_fargs=false,unsafe_comps=true,unsafe=true,passes=2' --mangle --output=docs/js/tutorial-04-vanilla-elm.js
node_modules/.bin/terser docs/js/tutorial-05-elm-animator-inline-1.js --no-rename --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters=true,keep_fargs=false,unsafe_comps=true,unsafe=true,passes=2' --mangle --output=docs/js/tutorial-05-elm-animator-inline-1.js
